### ISSUE TITLE
Big Mazes

### ISSUE THREAD

**Issue by devedse** [BoyBaykiller/IDKEngine#5]
Hello, I just encountered your repository after finding out about Mesh Shaders.
One of my hobbies is making mazes and making them as big as possible, I currently used MonoGame to be able to render them in 3D where I was able to render a Maze of about 16000*16000 in 3D.

I'm not that well versed in lower level 3D but I was wondering if you could maybe share some insights here if IDKEngine would be able to give a benefit in rendering an even larger maze.

In MonoGame I currently simply create 4 indices per wall (each with normals, positions, texture positions, etc.) and then 6 vertices. From what I understand is you should be able to generate vertices/indices with mesh shaders on the GPU?? Or do I completely misunderstand that?

Anyway, here's my Blazor version of the 3D maze generator (Inspired by the amazing Windows 95 screensaver :smile:):
https://3dmaze.devedse.duckdns.org/

![image](https://github.com/BoyBaykiller/IDKEngine/assets/2350015/7f0fb64e-51c2-4a7c-9c96-fa0d8ccab948)

**Comment by BoyBaykiller** [comment]
Hi. Note that IDKEngine is not a general purpose framework like MonoGame. Its a personal toy project with convoluted code to learn Graphics Programming and stuff. 

> I'm not that well versed in lower level 3D but I was wondering if you could maybe share some insights here if IDKEngine would be able to give a benefit in rendering an even larger maze.

IDKEngine only loads glTF models. If it was given the maze model as a single mesh the only technique I could see improving perf a lot, compared to what I think MonoGame is doing, is [meshlet frustum and occlusion culling](https://github.com/BoyBaykiller/IDKEngine/blob/fd9521bfaf187298e2b319c509850cab664eaafc/IDKEngine/res/shaders/DeferredRendering/GBuffer/MeshPath/task.glsl#L161) (using the mesh shader pipeline). Inside the maze a significant portion of meshlets would be culled early.

In your screenshot it says 2.068.315 walls, with non indexed rendering thats still only 2 million * 6 = 12 million vertex shader invocations. I feel like even without any optimizations it should be faster than 110 fps. Certainly is on my RX 5700 XT, what GPU do you have?

> In MonoGame I currently simply create 4 indices per wall (each with normals, positions, texture positions, etc.) and then 6 vertices. From what I understand is you should be able to generate vertices/indices with mesh shaders on the GPU?? Or do I completely misunderstand that?

You can generate vertex data "on the fly" using regular vertex shader as well.
You are not required to fill a vertex + index buffer from the CPU before hand. The vertex shader has a built-in `gl_VertexID` variable which can be used to calculate a vertex position or index into a small locally declared array of vertex data.

In the general case mesh shaders, just like vertex shaders, fetch the necessary data from pre filled buffers.
If you want to learn about mesh shaders I can recommed:
[From vertex shader to mesh shader](https://gpuopen.com/learn/mesh_shaders/mesh_shaders-from_vertex_shader_to_mesh_shader/) and [Introduction to Turing Mesh Shaders](https://developer.nvidia.com/blog/introduction-turing-mesh-shaders/).

---
Btw there seems to be a lot of aliasing, like its missing mipmaps. Having mipmaps will fix most of the aliasing and give improved texture sampling performance so that could be a good optimization opportunity.

**Comment by devedse** [comment]
Thank you, that was exactly the answer I was looking for. The main reason for it running at 110 fps is VSYNC and my fps calculator being slightly off.

I'll put the links you mentioned on my todo list whenever I'll be working on my maze generator again 😄 , thanks.

P.s. here's a screenshot of an 8192*8192 maze running with vsync disabled:

![image](https://github.com/BoyBaykiller/IDKEngine/assets/2350015/ca05fb6e-9d1d-45f6-89e0-2b8cd1a5dc95)

Anything bigger (16386*16386) tanks my performance though since the model doesn't seem to into GPU memory anymore (RTX 3080). <-- this was basically the issue I'm trying to solve, somehow being able to use less memory on my GPU while still being able to render the whole model in one go.

**Comment by BoyBaykiller** [comment]
Damn thats some pixel soup, might as well write garbage memory to screen lol.

Anyway I never specifically did maze rendering but since its a distinct task I am sure there exist very optimized solutions.
Depending on your needs you could probably just procedually generate a (infinite) maze in the vertex or fragment shader without any memory cost.
